### ISSUE TITLE
Cascading Options

### ISSUE THREAD

**Issue by jramonrod** [theque5t/rundeck-ui-mods#1] opened 2018-09-01 00:03 UTC
The check all button does not function when utilizing cascade options to fill out a field.
<img width="1664" alt="screen shot 2018-08-31 at 5 50 30 pm" src="https://user-images.githubusercontent.com/9137143/44940159-21bbb380-ad48-11e8-9c4e-36088dfd7d0c.png">

After checking in one of the boxes.
![imageedit_5_6261370234](https://user-images.githubusercontent.com/9137143/44940164-2d0edf00-ad48-11e8-9bd0-56e203fa4438.jpg)

**Comment by jramonrod** [comment] 2018-09-01 00:04
Apologies if I couldn't post much, it's company information.

**Comment by theque5t** [comment] 2018-09-01 00:16
Hello @Jose-R-Rodriguez , 
Couple of questions:
- what version of Rundeck are you running?
- Can you give me the exact steps to reproduce?
- Can you clarify what part is not functioning (e.g. button is not adding to the page, button is not checking all the boxes, etc.)?
When I tested with Rundeck 11.2.4, it was functioning properly with cascading remote options. I have tested the plugin with 11.2.5-1 and 3.0.1-20180803, but not with cascading remote options on those versions.

**Comment by theque5t** [comment] 2018-09-01 00:26
@Jose-R-Rodriguez Based on your screen shots, I'm guessing the issue is:
The button does not populate on the page for the "Hosts" option initially, and after you've selected the dependent option Farms. Is that correct?

**Comment by jramonrod** [comment] 2018-09-01 00:27
Thank you for your quick response. 

- Version 2.7.2

- The steps to fill out the hosts field in our case is to simply select a farm. This will populate the hosts field with various other options.

- The button is not being added to the page at all as you can tell in the image I have a farm selected, and my hosts field has been populated but the button is missing/not appearing.(I don't know exactly how it's supposed to function)

**Comment by jramonrod** [comment] 2018-09-01 00:28
@theque5t Yes the button does not appear once the host field has been populated. Again, I don't know if this is intended, but it seems like a bug to me.

**Comment by theque5t** [comment] 2018-09-01 00:28
@Jose-R-Rodriguez Understood. I'll take a look, and get back to you after I've done some investigating.

**Comment by theque5t** [comment] 2018-09-01 21:13
@Jose-R-Rodriguez Should be fixed now. You'll need to use the new build

**Comment by theque5t** [comment] 2018-09-01 21:15
@Jose-R-Rodriguez Let me know if it works, and I'll close this issue.

**Comment by jramonrod** [comment] 2018-09-01 21:16
@theque5t Alright I'll let you know on Monday when I head back to work thanks for the quick updates.

**Comment by jramonrod** [comment] 2018-09-04 16:15
Hello, sorry I forgot yesterday to get back to you, it seems like everything is working fine and the check all option comes up when the field is dynamically filled. 
Just an fyi, after restarting the server completely it started working with the old build, and then we swapped to the newer one. I don't know if that had some sort of effect, because like I said the old one started working.

**Comment by theque5t** [comment] 2018-09-06 21:27
@Jose-R-Rodriguez Glad it’s fixed now. I’ll close this issue.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Closed as completed** 2018-09-06 21:27 UTC
